In [1]:
print("hello")

hello


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report, confusion_matrix
import warnings
import pickle
from scipy import stats
warnings. filterwarnings( 'ignore')
plt.style.use( 'fivethirtyeight')


In [3]:
df = pd.read_csv(r"C:\Users\dharu\Documents\nan mudhalvan project\dataset\incd.csv")
df.head()


index                         County   FIPS   
0      0           US (SEER+NPCR)(1,10)      0  \
1      1  Autauga County, Alabama(6,10)   1001   
2      2  Baldwin County, Alabama(6,10)   1003   
3      3  Barbour County, Alabama(6,10)   1005   
4      4     Bibb County, Alabama(6,10)   1007   

  Age-Adjusted Incidence Rate(Ê) - cases per 100,000   
0                                               62.4  \
1                                               74.9   
2                                               66.9   
3                                               74.6   
4                                               86.4   

  Lower 95% Confidence Interval Upper 95% Confidence Interval   
0                          62.3                          62.6  \
1                          65.1                          85.7   
2                          62.4                          71.7   
3                          61.8                          89.4   
4                            71                         104.2   

  Average Annual Count Recent Trend   
0               214614      falling  \
1                   43       stable   
2                  170       stable   
3                   25       stable   
4                   23       stable   

  Recent 5-Year Trend (ˆ) in Incidence Rates Lower 95% Confidence Interval.1   
0                                       -2.5                              -3  \
1                                        0.5                           -14.9   
2                                          3                           -10.2   
3                                       -6.4                           -18.3   
4                                       -4.5                           -31.4   

  Upper 95% Confidence Interval.1  
0                              -2  
1                            18.6  
2                            18.3  
3                             7.3  
4                            32.9

In [4]:
df.shape

cat_cols = df.select_dtypes(include=['object']).columns
df_categorical = df[cat_cols]
df.dtypes



index                                                  int64
County                                                object
 FIPS                                                  int64
Age-Adjusted Incidence Rate(Ê) - cases per 100,000    object
Lower 95% Confidence Interval                         object
Upper 95% Confidence Interval                         object
Average Annual Count                                  object
Recent Trend                                          object
Recent 5-Year Trend (ˆ) in Incidence Rates            object
Lower 95% Confidence Interval.1                       object
Upper 95% Confidence Interval.1                       object
dtype: object

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
lb = LabelEncoder()
df.shape

(3141, 11)

In [7]:
df_encoded = df_categorical.apply(lb.fit_transform)
df_encoded.head()


County  Age-Adjusted Incidence Rate(Ê) - cases per 100,000   
0    2842                                                414   \
1     110                                                569    
2     119                                                472    
3     131                                                566    
4     201                                                696    

   Lower 95% Confidence Interval  Upper 95% Confidence Interval   
0                            416                            504  \
1                            444                            732   
2                            417                            594   
3                            411                            769   
4                            504                             45   

   Average Annual Count  Recent Trend   
0                   121             3  \
1                   235             5   
2                    83             5   
3                   149             5   
4                   130             5   

   Recent 5-Year Trend (ˆ) in Incidence Rates   
0                                         102  \
1                                         206   
2                                         320   
3                                         165   
4                                         145   

   Lower 95% Confidence Interval.1  Upper 95% Confidence Interval.1  
0                              228                               25  
1                               68                              212  
2                               21                              209  
3                              102                              640  
4                              250                              375

In [8]:
df_encoded['Recent Trend1'] =  df['Recent Trend'].map({'falling':1,'stable':2,'*':3,'rising':4,'_':5,'__':6})
df_encoded['index'] = df['index']
df_encoded['FIPS']  = df[' FIPS']
df_encoded.shape

(3141, 12)

In [9]:
df_encoded.describe()

County  Age-Adjusted Incidence Rate(Ê) - cases per 100,000   
count  3141.000000                                        3141.000000   \
mean   1570.000000                                         452.453677    
std     906.872924                                         230.423510    
min       0.000000                                           0.000000    
25%     785.000000                                         304.000000    
50%    1570.000000                                         478.000000    
75%    2355.000000                                         623.000000    
max    3140.000000                                         812.000000    

       Lower 95% Confidence Interval  Upper 95% Confidence Interval   
count                    3141.000000                    3141.000000  \
mean                      360.980898                     459.683222   
std                       190.232669                     290.783148   
min                         0.000000                       0.000000   
25%                       232.000000                     152.000000   
50%                       373.000000                     555.000000   
75%                       490.000000                     699.000000   
max                       697.000000                     868.000000   

       Average Annual Count  Recent Trend   
count           3141.000000   3141.000000  \
mean             192.877109      4.184336   
std              107.901776      1.643194   
min                0.000000      0.000000   
25%              103.000000      5.000000   
50%              188.000000      5.000000   
75%              285.000000      5.000000   
max              362.000000      5.000000   

       Recent 5-Year Trend (ˆ) in Incidence Rates   
count                                 3141.000000  \
mean                                   167.366444   
std                                    129.056312   
min                                      0.000000   
25%                                     37.000000   
50%                                    156.000000   
75%                                    259.000000   
max                                    400.000000   

       Lower 95% Confidence Interval.1  Upper 95% Confidence Interval.1   
count                      3141.000000                      3141.000000  \
mean                        204.674308                       318.141993   
std                         170.667332                       235.464451   
min                           0.000000                         0.000000   
25%                          58.000000                       119.000000   
50%                         156.000000                       272.000000   
75%                         342.000000                       519.000000   
max                         516.000000                       733.000000   

       Recent Trend1        index          FIPS  
count    3141.000000  3141.000000   3141.000000  
mean        2.251512  1570.000000  30392.281757  
std         0.880306   906.872924  15158.200839  
min         1.000000     0.000000      0.000000  
25%         2.000000   785.000000  18179.000000  
50%         2.000000  1570.000000  29177.000000  
75%         2.000000  2355.000000  45081.000000  
max         6.000000  3140.000000  56045.000000

In [10]:
x = df_encoded.drop(['Recent Trend1'],axis=1)
x = x.drop(['Recent Trend'],axis=1)
y=df_encoded['Recent Trend1']
print(x.shape,y.shape)
y.head()

(3141, 10) (3141,)


0    1
1    2
2    2
3    2
4    2
Name: Recent Trend1, dtype: int64

In [11]:
x_train, x_test, y_train, y_test = train_test_split(  x, y, test_size=0.2, random_state=0)

In [12]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=2)
X_train_res ,y_train_res = sm.fit_resample(x_train,y_train)

In [37]:
x_train.shape
t = pd.DataFrame(y_train)
t.describe()


Recent Trend1
count    2512.000000
mean        2.237659
std         0.867373
min         1.000000
25%         2.000000
50%         2.000000
75%         2.000000
max         6.000000

In [14]:
def tree_classifier(x_train, x_test, y_train_res, y_test):
    classifier_tree = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    classifier_tree .fit(x_train,y_train)
    y_pred = classifier_tree.predict(x_test)
    cm = confusion_matrix(y_test, y_pred)
    return print(f"Train score: { classifier_tree.score(x_train,y_train)}\nTest score:{classifier_tree.score(x_test,y_test)}"),print(cm)

In [15]:
from sklearn.naive_bayes import GaussianNB
def naive_classifier(x_train,x_test, y_train, y_test) :
    classifier_naive = GaussianNB()
    classifier_naive.fit(x_train,y_train)
    y_pred = classifier_naive.predict(x_test)
    cm = confusion_matrix(y_test,y_pred)
    pickle.dump(classifier_naive,open('naivemodel.pkl','wb'))
    return print("Train Score: ",classifier_naive.score(x_train,y_train),"Test Score : ",classifier_naive.score(x_test,y_test)),print(cm)

In [16]:
# import xgboost
# def xgboost_classifier(x_train,x_test,y_train,y_test):
#   classifier_xg=xgboost.XGBClassifier()
#   classifier_xg.fit(x_train,y_train)
#   y_pred = classifier_xg.predict(x_test)
#   cm = confusion_matrix(y_test,y_pred)
#   return print(f"train Score:{classifier_xg.score(x_train,y_train)}\nTest Score:{classifier_xg.score(x_test,y_test)}"),print(cm)

In [17]:
def knn_classifier(X_train,X_test,y_train,y_test):
    classifier_knn = KNeighborsClassifier(metric = "minkowski",p = 2)
    classifier_knn.fit(X_train,y_train)
    y_pred = classifier_knn.predict(X_test)
    cm = confusion_matrix(y_test,y_pred)
    return print(f"train Score : {classifier_knn.score(X_train,y_train)}\ntest Score:{classifier_knn.score(X_test,y_test)}"),print(cm)

In [18]:
def forest_classifier(X_train,X_test,y_train,y_test):
    classifier_forest = RandomForestClassifier(criterion= 'entropy',random_state = 0)
    classifier_forest.fit(X_train,y_train)
    y_pred = classifier_forest.predict(X_test)
    cm = confusion_matrix(y_test,y_pred)
    return print(f"train score:{classifier_forest.score(X_train,y_train)}\ntest Score:{classifier_forest.score(X_test,y_test)}"),print(cm)

In [19]:
from sklearn.svm import SVC
def svm_classifier(X_train,X_test,y_train,y_test):
    classifier_svm = SVC(kernel='rbf',random_state=0)
    classifier_svm.fit(X_train,y_train)
    y_pred = classifier_svm.predict(X_test)
    cm = confusion_matrix(y_test,y_pred)
    return print(f"Train score:{classifier_svm.score(X_train,y_train)}\ntest score:{classifier_svm.score(X_test,y_test)}"),print(cm)

In [20]:
naive_classifier(x_train,x_test, y_train, y_test)
knn_classifier(x_train,x_test,y_train,y_test)
forest_classifier(x_train,x_test,y_train,y_test)
svm_classifier(x_train,x_test,y_train,y_test)


Train Score:  0.982484076433121 Test Score :  0.9809220985691574
[[ 24   8   0   0   0   0]
 [  0 483   0   2   0   0]
 [  1   0  53   0   0   0]
 [  0   1   0   6   0   0]
 [  0   0   0   0  47   0]
 [  0   0   0   0   0   4]]
train Score : 0.9164012738853503
test Score:0.9014308426073132
[[  2  30   0   0   0   0]
 [  8 474   3   0   0   0]
 [  1  13  40   0   0   0]
 [  0   7   0   0   0   0]
 [  0   0   0   0  47   0]
 [  0   0   0   0   0   4]]
train score:1.0
test Score:0.9984101748807631
[[ 32   0   0   0   0   0]
 [  0 485   0   0   0   0]
 [  0   0  54   0   0   0]
 [  0   1   0   6   0   0]
 [  0   0   0   0  47   0]
 [  0   0   0   0   0   4]]
Train score:0.7738853503184714
test score:0.7710651828298887
[[  0  32   0   0   0   0]
 [  0 485   0   0   0   0]
 [  0  54   0   0   0   0]
 [  0   7   0   0   0   0]
 [  0  47   0   0   0   0]
 [  0   4   0   0   0   0]]


(None, None)

In [21]:


pickled_model = pickle.load(open('naivemodel.pkl','rb'))
a=pickled_model.predict([[1.413524,1.4053,218.0,87.0,573.0,223.0,122.0,449.0,579.0,1798.0]])
int(a)



2

In [32]:
x.head(50)
y.describe()


count    3141.000000
mean        2.251512
std         0.880306
min         1.000000
25%         2.000000
50%         2.000000
75%         2.000000
max         6.000000
Name: Recent Trend1, dtype: float64

In [27]:
y.head(
)

0    1
1    2
2    2
3    2
4    2
Name: Recent Trend1, dtype: int64

In [40]:
x_train.tail()

County  Age-Adjusted Incidence Rate(Ê) - cases per 100,000   
763     2378                                                663   \
835     1341                                                243    
1653      14                                                418    
2607    1039                                                257    
2732    2601                                                  0    

      Lower 95% Confidence Interval  Upper 95% Confidence Interval   
763                             495                            851  \
835                             150                            504   
1653                            310                            631   
2607                            198                            473   
2732                              0                              0   

      Average Annual Count  Recent 5-Year Trend (ˆ) in Incidence Rates   
763                    180                                           8  \
835                     14                                          33   
1653                   139                                         373   
2607                   149                                          46   
2732                   182                                           0   

      Lower 95% Confidence Interval.1  Upper 95% Confidence Interval.1  index   
763                                75                              186    763  \
835                               147                               75    835   
1653                               42                              353   1653   
2607                              247                               95   2607   
2732                                0                                0   2732   

       FIPS  
763   18135  
835   19095  
1653  31001  
2607  48171  
2732  48421